-- ─────────────────────────────────────────────
-- 003 – Gold Layer: aggregated metrics + dims
-- ─────────────────────────────────────────────

-- Fact: enriched price snapshots
CREATE TABLE IF NOT EXISTS fact_stock_price (
    id             BIGSERIAL PRIMARY KEY,
    symbol         VARCHAR(16)     NOT NULL,
    event_time     TIMESTAMPTZ     NOT NULL,
    price          NUMERIC(18, 4)  NOT NULL,
    previous_price NUMERIC(18, 4),
    price_change   NUMERIC(18, 4),
    pct_change     NUMERIC(10, 4),
    moving_avg_5   NUMERIC(18, 4),
    moving_avg_20  NUMERIC(18, 4),
    volatility     NUMERIC(10, 6),
    volume         BIGINT,
    anomaly_flag   BOOLEAN         NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_fact_symbol ON fact_stock_price (symbol);
CREATE INDEX IF NOT EXISTS idx_fact_event_time ON fact_stock_price (event_time DESC);
CREATE INDEX IF NOT EXISTS idx_fact_anomaly ON fact_stock_price (anomaly_flag) WHERE anomaly_flag = TRUE;

-- Dimension: stock metadata
CREATE TABLE IF NOT EXISTS dim_stock (
    stock_id     SERIAL PRIMARY KEY,
    symbol       VARCHAR(16)  NOT NULL UNIQUE,
    company_name VARCHAR(256) NOT NULL,
    sector       VARCHAR(128),
    exchange     VARCHAR(64)
);

-- Dimension: time (populated lazily by the ETL)
CREATE TABLE IF NOT EXISTS dim_time (
    time_id  BIGSERIAL PRIMARY KEY,
    ts       TIMESTAMPTZ NOT NULL UNIQUE,
    date     DATE        NOT NULL,
    hour     SMALLINT    NOT NULL,
    minute   SMALLINT    NOT NULL,
    weekday  VARCHAR(16) NOT NULL,
    month    SMALLINT    NOT NULL,
    year     SMALLINT    NOT NULL
);

-- Alerts generated by anomaly detection
CREATE TABLE IF NOT EXISTS stock_alerts (
    id          BIGSERIAL PRIMARY KEY,
    symbol      VARCHAR(16)    NOT NULL,
    alert_type  VARCHAR(64)    NOT NULL,  -- PRICE_SPIKE, HIGH_VOLUME, MA_CROSSOVER
    message     TEXT           NOT NULL,
    severity    VARCHAR(16)    NOT NULL DEFAULT 'MEDIUM',  -- LOW / MEDIUM / HIGH
    price       NUMERIC(18, 4),
    pct_change  NUMERIC(10, 4),
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_symbol ON stock_alerts (symbol);
CREATE INDEX IF NOT EXISTS idx_alerts_created ON stock_alerts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON stock_alerts (severity);
